apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: irrigation-system
type: Opaque
stringData:
  db-username: irrigation_user
  db-password: irrigation_pass
  root-password: root
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: irrigation-system
type: Opaque
stringData:
  username: admin
  password: admin
