server:
  port: 8082

spring:
  application:
    name: ms-arrosage
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: false